version: "3"
services:
  server:
    build: ./server
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/messenger
      NODE_ENV: development
      SESSION_SECRET: "your session secret"
      CHOKIDAR_USEPOLLING: "true"
      PORT: 3001
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app/
      - /app/node_modules
    container_name: server
    networks:
      - webapp
      - database

  postgres:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: messenger
    container_name: postgres
    networks:
      - database

  client:
    build:
      context: ./client
    depends_on:
      - server
    networks:
      - webapp
    ports:
      - 3000:3000
    container_name: client
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ./client:/app/

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge
